#!/usr/bin/env python3
import argparse
import os
import pathlib
import shlex
import subprocess
import sys
import tempfile


def resolve_bob_path(cli_bob):
    if cli_bob:
        return cli_bob
    env_bob = os.environ.get("BOB")
    if env_bob:
        return env_bob
    dynamo_home = os.environ.get("DYNAMO_HOME")
    if dynamo_home:
        return os.path.join(dynamo_home, "share", "java", "bob.jar")
    return ""


def write_cpp(output_path, spc_bytes, source_paths, command_line):
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="ascii") as out:
        out.write("// Generated by gen_shaders.py. Do not edit.\n")
        out.write("// Command: {}\n".format(command_line))
        out.write("// Sources:\n")
        for path in source_paths:
            out.write("//   {}\n".format(path))
        out.write("\n")
        out.write("#include <stdint.h>\n")
        out.write("#include <dmsdk/ddf/ddf.h>\n")
        out.write("#include <dmsdk/graphics/graphics.h>\n")
        out.write("#include <graphics/graphics_ddf.h>\n")
        out.write("\n")
        out.write("static uint8_t RIVEMODEL_BLIT_SPC[] = {\n")
        for i in range(0, len(spc_bytes), 12):
            chunk = spc_bytes[i : i + 12]
            line = ", ".join("0x{:02x}".format(b) for b in chunk)
            out.write("    {},\n".format(line))
        out.write("};\n")
        out.write("static const uint32_t RIVEMODEL_BLIT_SPC_SIZE = sizeof(RIVEMODEL_BLIT_SPC);\n")
        out.write("\n")
        out.write("namespace dmGraphics\n")
        out.write("{\n")
        out.write("    ShaderDesc* CreateRiveModelBlitShaderDesc()\n")
        out.write("    {\n")
        out.write("        static ShaderDesc* shader_desc = 0;\n")
        out.write("        if (!shader_desc)\n")
        out.write("        {\n")
        out.write("            void* msg = 0;\n")
        out.write("            dmDDF::Result result = dmDDF::LoadMessage(RIVEMODEL_BLIT_SPC,\n")
        out.write("                                                      RIVEMODEL_BLIT_SPC_SIZE,\n")
        out.write("                                                      ShaderDesc::m_DDFDescriptor,\n")
        out.write("                                                      &msg);\n")
        out.write("            if (result != dmDDF::RESULT_OK)\n")
        out.write("            {\n")
        out.write("                return 0;\n")
        out.write("            }\n")
        out.write("            shader_desc = (ShaderDesc*) msg;\n")
        out.write("        }\n")
        out.write("        return shader_desc;\n")
        out.write("    }\n")
        out.write("}\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--bob", default="")
    parser.add_argument("--platform", required=True)
    parser.add_argument("--content-root", required=True)
    parser.add_argument("--vertex", required=True)
    parser.add_argument("--fragment", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    bob_path = resolve_bob_path(args.bob)
    if not bob_path or not os.path.isfile(bob_path):
        print("bob.jar not found. Set --bob, BOB, or DYNAMO_HOME.", file=sys.stderr)
        return 1

    content_root = pathlib.Path(args.content_root).resolve()
    vertex_path = pathlib.Path(args.vertex).resolve()
    fragment_path = pathlib.Path(args.fragment).resolve()
    output_path = pathlib.Path(args.output).absolute()

    if not vertex_path.is_file() or not fragment_path.is_file():
        print("Shader inputs not found.", file=sys.stderr)
        return 1

    with tempfile.TemporaryDirectory() as tmpdir:
        spc_path = pathlib.Path(tmpdir) / "rivemodel_blit.spc"
        cmd = [
            "java",
            "-classpath",
            bob_path,
            "com.dynamo.bob.pipeline.ShaderProgramBuilder",
            str(vertex_path),
            str(fragment_path),
            str(spc_path),
            args.platform,
            str(content_root),
        ]
        cmd_str = " ".join(shlex.quote(part) for part in cmd)
        subprocess.check_call(cmd)

        spc_bytes = spc_path.read_bytes()
        write_cpp(output_path, spc_bytes, [vertex_path, fragment_path], cmd_str)

    return 0


if __name__ == "__main__":
    sys.exit(main())
