function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if not action_id or action_id == hash("touch") then
		if action.pressed then
			rive.pointer_down("#hud", action.screen_x, action.screen_y)
		elseif action.released then
			rive.pointer_up("#hud", action.screen_x, action.screen_y)
		else
			rive.pointer_move("#hud", action.screen_x, action.screen_y)
		end
	end
end
