name: Rive Build and Commit
description: Clone Rive runtime, build for a platform, optionally upload artifact, and commit changes

inputs:
  platform:
    description: Target platform (e.g., x86_64-linux, arm64-macos, arm64-android, ...)
    required: true
  rive_repo_url:
    description: Rive runtime repo URL
    required: true
    default: https://github.com/rive-app/rive-runtime.git
  rive_ref:
    description: Rive runtime ref (branch/tag)
    required: false
    default: ""
  rive_sha:
    description: Rive runtime commit SHA (overrides ref)
    required: false
    default: ""
  upload_artifact:
    description: Upload tarball artifact
    required: true
    default: "false"
  commit_message:
    description: Optional commit message suffix
    required: false
    default: ""
  push_changes:
    description: Push changes back to the same branch
    required: true
    default: "true"

runs:
  using: composite
  steps:
    - name: Clone Rive runtime and set RIVE_ROOT
      shell: bash
      run: |
        set -euo pipefail
        RIVE_TMP_DIR=$(mktemp -d)
        echo "RIVE_ROOT=${RIVE_TMP_DIR}" >> "$GITHUB_ENV"
        url="${{ inputs.rive_repo_url }}"
        ref="${{ inputs.rive_ref }}"
        sha="${{ inputs.rive_sha }}"
        echo "Cloning Rive runtime from: ${url}"
        if [ -n "$sha" ]; then
          git -c core.autocrlf=false -c core.eol=lf clone --depth 1 "$url" "$RIVE_TMP_DIR"
          (cd "$RIVE_TMP_DIR" && git fetch --depth 1 origin "$sha" && git checkout -f "$sha")
        elif [ -n "$ref" ]; then
          git -c core.autocrlf=false -c core.eol=lf clone --depth 1 --branch "$ref" "$url" "$RIVE_TMP_DIR"
        else
          git -c core.autocrlf=false -c core.eol=lf clone --depth 1 "$url" "$RIVE_TMP_DIR"
        fi
        # Double-check repo config to avoid CRLF breaking patch apply
        (cd "$RIVE_TMP_DIR" && git config core.autocrlf false && git config core.eol lf)
        echo "RIVE_ROOT set to: $RIVE_TMP_DIR"

    - name: Ensure clean Rive repo
      shell: bash
      run: |
        set -euo pipefail
        if [ -d "${RIVE_ROOT}/.git" ]; then
          cd "${RIVE_ROOT}"
          if [ -n "$(git status --porcelain)" ]; then
            echo "Pending changes detected; resetting Rive repo"
            git reset --hard
          else
            echo "Rive repo is clean"
          fi
        fi

    - name: Show context
      shell: bash
      run: |
        echo "Branch: ${GITHUB_REF_NAME:-unknown}"
        echo "RIVE_ROOT: ${RIVE_ROOT:-not-set}"
        echo "Platform: ${{ inputs.platform }}"
        git --version
        git status

    - name: Build Rive runtime
      shell: bash
      env:
        INPUT_PLATFORM: ${{ inputs.platform }}
      run: |
        set -euo pipefail
        platform="$INPUT_PLATFORM"
        echo "Running: ./utils/build_rive_runtime.sh ${platform} ${RIVE_ROOT}"
        bash utils/build_rive_runtime.sh "${platform}" "${RIVE_ROOT}"

    - name: Pack artifacts (optional)
      if: ${{ inputs.upload_artifact == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        paths=()
        [ -d defold-rive/lib ] && paths+=(defold-rive/lib)
        [ -d defold-rive/include ] && paths+=(defold-rive/include)
        if [ ${#paths[@]} -eq 0 ]; then
          echo "No artifact directories found (defold-rive/lib, defold-rive/include)."
          exit 0
        fi
        echo "Packing: ${paths[*]}"
        tar -czf "branch-artifacts-${GITHUB_REF_NAME}.tgz" "${paths[@]}"

    - name: Upload artifact (optional)
      if: ${{ inputs.upload_artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: branch-artifacts-${{ github.ref_name }}
        path: branch-artifacts-${{ github.ref_name }}.tgz
        if-no-files-found: ignore

    - name: Commit and push changes (optional)
      if: ${{ inputs.push_changes == 'true' }}
      shell: bash
      env:
        COMMIT_SUFFIX: ${{ inputs.commit_message }}
      run: |
        set -euo pipefail
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        add_paths=()
        [ -d defold-rive/lib ] && add_paths+=(defold-rive/lib)
        [ -d defold-rive/include ] && add_paths+=(defold-rive/include)
        if [ ${#add_paths[@]} -gt 0 ]; then
          git add -v "${add_paths[@]}" || true
        fi
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        msg="ci: update artifacts on ${GITHUB_REF_NAME} [skip ci]"
        if [ -n "${COMMIT_SUFFIX}" ]; then
          msg="$msg - ${COMMIT_SUFFIX}"
        fi
        git commit -m "$msg"
        max_attempts=3
        attempt=1
        until [ $attempt -gt $max_attempts ]; do
          echo "Attempt $attempt: rebase + push"
          if git pull --rebase origin "${GITHUB_REF_NAME}"; then
            if git push origin HEAD:"${GITHUB_REF_NAME}"; then
              echo "Push succeeded"
              break
            fi
          else
            echo "Rebase failed; aborting and retrying"
            git rebase --abort || true
          fi
          attempt=$((attempt+1))
          sleep $((attempt*2))
        done
        if [ $attempt -gt $max_attempts ]; then
          echo "Push failed after $max_attempts attempts"
          exit 1
        fi

    - name: Post-commit status
      if: ${{ always() }}
      shell: bash
      run: |
        git --no-pager log -1 --oneline || true
        git status || true
