[rive]
help = Settings for Rive extension
group = Components

max_instance_count.type = integer
max_instance_count.default = 128

use_threads.type = bool
use_threads.default = 0
use_threads.help = Run Rive command processing on a worker thread
