name: Build with bob

on: [push, pull_request]

env:
  PLUGIN_SO: './defold-rive/plugins/lib/x86_64-linux/libRiveExt.so'

jobs:
  check_shared_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check shared dependencies
        run: |
          ldd ${{ env.PLUGIN_SO }}
          if ldd ${{ env.PLUGIN_SO }} | grep -e 'not found' ; then (exit 1); fi

  build:
    needs: check_shared_dependencies
    uses: defold/github-actions-common/.github/workflows/bob.yml@master
    with:
      ignored_platforms: '[{"platform": "armv7-android"}]'

